Port: ":8080"
DatabaseType:                    "postgres"
DatabaseName:                    "host=localhost user=jess password=abc dbname=test sslmode=disable"
ExpirationTime:                  5m
CleanTime:                       30s
BaseURL:                         "127.0.0.1"
ListenerExpirationTime:          3m
RecentlyCompletedExpirationTime: 1m
HTTPS: false
LogRequests: false
Token: "748312907487203129347q97"
MaxOpenDBConnections: 32