Port: ":8081"
DatabaseType:                    "sqlite3"
DatabaseName:                    "test.db"
ExpirationTime:                  5m
CleanTime:                       30s
BaseURL:                         "127.0.0.1"
ListenerExpirationTime:          3m
RecentlyCompletedExpirationTime: 1m
HTTPS: false
LogRequests: true
Token: "748312907487203129347q97"